runtime: python39
entrypoint: gunicorn -b :$PORT app.server:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.5

env_variables:
  CLOUD_STORAGE_BUCKET: "robust-caldron-387203.appspot.com"

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
